[package]
name = "tower-sessions-r2d2-sqlite-store"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
r2d2 = "0.8.10"
r2d2_sqlite = "0.27.0"
rmp-serde = "1.3.0"
thiserror = "2.0.12"
time = "0.3.41"
tower-sessions-core = "0.14.0"
